### ISSUE TITLE
Please allow download from third party launchers

### ISSUE THREAD

**Issue by blackd** [Lupicus/SpawnerFix#1]
With the new curseforge REST API rollout your mods are currently only accessible using the curseforge site and the curseforge app.

Could you please allow access for launchers like ATLauncher.

For more info https://support.curseforge.com/en/support/solutions/articles/9000207877-project-distribution-toggle

**Comment by Lupicus** [comment]
We have looked into this. We are not comfortable that we understand all the implications of changing the setting right now.  We will revisit it later, perhaps in the fall.

**Comment by blackd** [comment]
I just find it strange that the authors of a MIT licensed software impose restrictions on the distribution channels.

To be honest I doubt that there will be any effect on the rewards program. I really doubt any of the third party downloads have ever counted. I doubt any downloads by people with adblockers ever counted.

IMO the whole thing has a goal to scare the devs so overwolf can remove access altogether.

**Comment by DDriggs00** [comment]
Here's a more detailed explanation of some of the downsides to this setting:  https://gist.github.com/copygirl/7d45bad739453d2be61138cebafce04c
